export enum TranslateBookingKeys {
    alreadyUsed= 'alreadyUsed',
    bookedBy = 'bookedBy',
    bookingDeleted = 'bookingDeleted',
    bookingDuration = 'bookingDuration',
    bookFor ='bookFor',
    bookingSaved= 'bookingSaved',
    cancelReservation = 'cancelReservation',
    cantBook = 'cantBook',
    decreaseBookDuration = 'decreaseBookDuration',
    fromTo ='fromTo',
    handleBook = 'handleBook',
    increaseBookDuration = 'increaseBookDuration',
    lastMinute = 'lastMinute',
    reloadWithNewData= 'reloadWithNewData',
    roomIsFree = 'roomIsFree',
    slotAlreadyBooked = 'slotAlreadyBooked',
    'slotIs-free'= 'slotIs-free',
    'slotIs-self-booked' = 'slotIs-self-booked',
    'slotIs-booked' = 'slotIs-booked',
    unknowBookingTime = 'unknowBookingTime'
}
