name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Test coverage
        run: npm run test:ci

      - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

      - name: Linter
        run: npm run eslint:ci

      - name: Build
        run: npm run build
